Feature/step4 enhance logging system
hegej/TerminalDungeonQuest pull request #4
Opened 2024-08-26 12:06 UTC by hegej

Added Spectre console, unicode emojis,
Addedd random attributes and check to make the teams more balanced.

Functions for display during play.

2024-08-26 16:32 UTC, glennwiz requested changes

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Interfaces/IBattleLogger.cs
> +        void LogBattleStart();
Ville nok ikke hatt 3 forkjelige logg funkejner,, jeg ville valgt en log funkjon og heller hatt overloads på den

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/WarriorParameters.cs
> +            Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/RogueParameters.cs
> +            Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/PaladinParameters.cs
> +            Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/MageParameters.cs
> +            Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/HunterParameters.cs
> +            Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameLogic/Characters/CharacterParameters/EnemyParameters.cs
> +        private static Random rand = new Random();
du  bør flytte denne ut i et global static object, du trenger bare et random object, ikke lage nytt object kver gang du lager en char.

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameSimulator/GameConsoleLogger.cs
> +    public class GameConsoleLogger : IBattleLogger
Denne føles veldig merkelig denne classen,,, eneste den Gjør er og proxyer til noen static methods? koffer et Interface her?

2024-08-26 16:32 UTC, glennwiz commented on DungeonGameSimulator/GameConsoleLogger.cs
> +    public class GameConsoleLogger : IBattleLogger
Koffer ikke bruke disse static metodene direkte?

2024-08-26 16:37 UTC, glennwiz commented on DungeonGameSimulator/GameConsoleLogger.cs
> +    public class GameConsoleLogger : IBattleLogger
en IBattleLogger vil du foraltid kun ha 1 type av, 

Ikke som feks vist du hadde en  ICharacter som du kan genere opp mange forkjelige typer av.
_
Warrior : ICharacter
Rouge : ICharacter
Hunter : ICharater

Osv osv...
IBattleLogger  skaper bare unødvendig complexitet og ser ikke grun til og ha den ,,,, mye hellr call direkte di statisk metodene droppe den Interfacet (IBattleLogger ) og classen (GameConsoleLogger) helt

ikke bruk Interfaces uten du har et behov..

2024-09-17 09:47 UTC, hegej commented on DungeonGameSimulator/GameConsoleLogger.cs
> +    public class GameConsoleLogger : IBattleLogger
Men hvordan skal jeg løse det da, med at BattleEngine ikke kan nå klassene i Console app, Siden den er endel av classLib prosjektet?
Fordi jeg endret alle Battlelogg "calls" til gameConsole funksjoner, for å bruke SPectre.Console. Hvordan ville du anbefalt meg å løse det anderledes?

2024-09-18 11:08 UTC, merged